import { writeFileSync } from 'fs'

const lines = [
'import { getArticulo } from "../../../lib/sanity"',
'',
'export default async function ArticuloPage({ params }: { params: Promise<{ slug: string }> }) {',
'  const { slug } = await params',
'  const articulo = await getArticulo(slug)',
'',
'  if (!articulo) {',
'    return (',
'      <main style={{fontFamily: "system-ui, sans-serif", minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center"}}>',
'        <div style={{textAlign: "center"}}>',
'          <h1 style={{fontSize: "24px", marginBottom: "16px"}}>Articulo no encontrado</h1>',
'          <a href="/" style={{color: "#2d6a4f"}}>Volver al inicio</a>',
'        </div>',
'      </main>',
'    )',
'  }',
'',
'  return (',
'    <main style={{fontFamily: "system-ui, sans-serif", minHeight: "100vh", backgroundColor: "#f8f4ef"}}>',
'      <header style={{background: "linear-gradient(135deg, #2d3a4a 0%, #1a2634 100%)", padding: "20px 48px", display: "flex", justifyContent: "space-between", alignItems: "center", borderBottom: "3px solid #c9a84c"}}>',
'        <a href="/" style={{fontWeight: "800", fontSize: "18px", color: "#f0e6cc", textDecoration: "none", fontFamily: "Georgia, serif"}}>Andres Gutierrez</a>',
'        <a href="/#articulos" style={{fontSize: "13px", color: "#b8c4cc", textDecoration: "none"}}>Volver a articulos</a>',
'      </header>',
'      <article style={{maxWidth: "780px", margin: "0 auto", padding: "80px 48px"}}>',
'        <p style={{fontSize: "12px", color: "#2d6a4f", fontWeight: "700", letterSpacing: "2px", textTransform: "uppercase", marginBottom: "20px"}}>',
'          {articulo.fechaPublicacion ? new Date(articulo.fechaPublicacion).toLocaleDateString("es-CO", {year: "numeric", month: "long", day: "numeric"}) : ""}',
'        </p>',
'        <h1 style={{fontSize: "42px", fontWeight: "800", lineHeight: "1.2", marginBottom: "24px", letterSpacing: "-1px", color: "#2d3a4a", fontFamily: "Georgia, serif"}}>{articulo.titulo}</h1>',
'        <p style={{fontSize: "18px", color: "#666", lineHeight: "1.8", marginBottom: "48px", borderBottom: "1px solid #e8e0d5", paddingBottom: "32px"}}>{articulo.resumen}</p>',
'        <div style={{fontSize: "17px", lineHeight: "1.9", color: "#333"}}>',
'          <p style={{whiteSpace: "pre-wrap"}}>{articulo.contenido}</p>',
'        </div>',
'      </article>',
'      <footer style={{background: "linear-gradient(135deg, #1a2634 0%, #2d3a4a 100%)", padding: "40px 48px", borderTop: "3px solid #c9a84c", marginTop: "80px"}}>',
'        <div style={{maxWidth: "780px", margin: "0 auto", textAlign: "center"}}>',
'          <span style={{fontSize: "14px", color: "#f0e6cc", fontFamily: "Georgia, serif"}}>Andres Gutierrez</span>',
'        </div>',
'      </footer>',
'    </main>',
'  )',
'}',
]

writeFileSync('app/articulos/[slug]/page.tsx', lines.join('\n'), 'utf8')
console.log('OK')